---
- name: Download Fzf
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf
    dest: "{{ ansible_env.HOME }}/.fzf"
    clone: true
    update: true
    version: master

- name: Install Fzf Binary
  ansible.builtin.shell: |
    {{ ansible_env.HOME }}/.fzf/install --bin
  register: fzf_install
  changed_when: fzf_install.rc != 0

# code: language=ansible
