---
- name: Set list of additional Apt Packages if not Set
  ansible.builtin.set_fact:
    additional_pkgs:
      - curl
      - git-flow
      - git-lfs
      - lftp
      - python3-pip
      - python3-venv
      - remmina
      - rofi
      - silversearcher-ag
      - wget
      - xclip
    when: additional_pkgs is not defined
  tags: skip_ansible_lint

- name: Install Additional Apt Packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ additional_pkgs }}"

# vim: ft=yaml.ansible:
