---
- name: Set list of additional Apt Packages if not Set
  ansible.builtin.set_fact:
    additional_pkgs:
      - rofi
      - python3-venv
      - git-flow
      - git-lfs
    when: additional_pkgs is not defined
  tags: skip_ansible_lint

- name: Install Additional Apt Packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ additional_pkgs }}"

# vim: ft=yaml.ansible:
