---
roles:
  - name: bodsch.snapd
  - name: darkwizard242.googlechrome
  - name: gantsign.visual-studio-code
  - name: darkwizard242.googlechrome

collections:
  - community.general
  - ansible.posix
