---
- name: Configure Ubuntu Workstation
  hosts: workstations
  remote_user: kaskshad

  pre_tasks:
    - name: Update System
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Create ansible Temp dir
      become: true
      ansible.builtin.file:
        path: /root/.ansible/tmp
        state: directory
        owner: root
        group: root
        mode: "0775"

    - name: Create the Anisble User Temp Directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.ansible/tmp"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0775"

    - name: Ensure User Applications Dir Exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/applications"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0775"

  roles:
    - role: nodejs
      tags: [node, nodejs]
    - role: shell
      tags: shell
    - role: nvim
      tags: [nvim, neovim]
    - role: fonts
      tags: [font, fonts]
    - role: plasma
      tags: plasma
    - role: firefox
      tags: firefox

# vim: ft=yaml.ansible:
