---
- name: Set Default Plasma Packages
  ansible.builtin.set_fact:
    plasma_packages:
      - flameshot
      - ksshaskpass
      - kwin-bismuth
      - yakuake
  when: plasma_packages is not defined

- name: Add kubuntu backports PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:kubuntu-ppa/backports-extra
    state: present

- name: Update Plasma
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Check for Required Restart
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Restart and wait to connect if Restart is Required
  ansible.builtin.reboot:
    connect_timeout: 30
  when: reboot_required_file.stat.exists

- name: Install Additional Plasma Packages
  become: true
  ansible.builtin.apt:
    package: "{{ item }}"
  with_items: "{{ plasma_packages }}"

# vim: ft=yaml.ansible
