---
- name: Set Default Plasma Packages
  ansible.builtin.set_fact:
    plasma_packages:
      - flameshot
      - ksshaskpass
      - kwin-bismuth
      - yakuake
  when: plasma_packages is not defined

- name: Add kubuntu backports PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:kubuntu-ppa/backports-extra
    state: present

- name: Update Plasma
  become: true
  ansible.builtin.apt:
    upgrade: full
    update_cache: true

- name: Install Additional Plasma Packages
  become: true
  ansible.builtin.apt:
    package: "{{ item }}"
  with_items: "{{ plasma_packages }}"

# vim: ft=yaml.ansible
