---
- name: Enable libvirtd
  become: true
  ansible.builtin.systemd:
    name: libvirtd
    enabled: true
    masked: false
    state: restarted
  listen: "enable libvirtd"

# vim: ts=2 tw=2 et ft=yaml.ansible
