---
- name: Set Font Install  Path
  ansible.builtin.set_fact:
    fonts_dir: "{{ ansible_env.HOME + '/.local/share/fonts' }}"

- name: Create Local Fonts Directory
  ansible.builtin.file:
    path: "{{ fonts_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"

- name: Install Font if Needed
  ansible.builtin.include_tasks:
    install_font.yml
  with_items: "{{ font_names | default(['FiraCode', 'SourceCodePro', 'JetBrainsMono']) }}"

- name: Clear Font Cache
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.cache/fontconfig"
    state: absent

- name: Update Font Cache
  ansible.builtin.command:
    cmd: /usr/bin/fc-cache -f
    creates: "{{ ansible_env.HOME }}/.cache/fontconfig"

# code: language=ansible
# vim: ft=yaml.ansible
